#################################
# TeamOS picom (forest)
#################################

backend = "glx";
vsync = true;
use-damage = true;

shadow = true;
shadow-radius = 22;
shadow-opacity = 0.62;
shadow-offset-x = -16;
shadow-offset-y = -16;
shadow-exclude = [
  "name = 'Notification'",
  "class_g = 'Rofi'",
  "class_g ?= 'Dunst'",
  "window_type = 'dock'",
  "window_type = 'desktop'"
];

fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-delta = 4;

inactive-opacity = 0.88;
active-opacity = 1.0;
frame-opacity = 0.9;

corner-radius = 12;
round-borders = 1;
rounded-corners-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'"
];

blur-method = "dual_kawase";
blur-strength = 4;

wintypes:
{
  dock = { shadow = false; clip-shadow-above = true; };
  dnd = { shadow = false; };
  popup_menu = { opacity = 0.96; };
  dropdown_menu = { opacity = 0.96; };
};
