#################################
# TeamOS picom (ember)
#################################

backend = "glx";
vsync = true;
use-damage = true;

shadow = true;
shadow-radius = 20;
shadow-opacity = 0.58;
shadow-offset-x = -15;
shadow-offset-y = -15;
shadow-exclude = [
  "name = 'Notification'",
  "class_g = 'Rofi'",
  "class_g ?= 'Dunst'",
  "window_type = 'dock'",
  "window_type = 'desktop'"
];

fading = true;
fade-in-step = 0.04;
fade-out-step = 0.04;
fade-delta = 4;

inactive-opacity = 0.94;
active-opacity = 1.0;
frame-opacity = 0.96;

corner-radius = 9;
round-borders = 1;
rounded-corners-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'"
];

blur-method = "none";

wintypes:
{
  dock = { shadow = false; clip-shadow-above = true; };
  dnd = { shadow = false; };
  popup_menu = { opacity = 0.97; };
  dropdown_menu = { opacity = 0.97; };
};