ob_title_layout="LIMC"
margin_top="56"
margin_bottom="76"
margin_left="12"
margin_right="12"
topbar_size="98% 44"
topbar_margin="12 10"
topbar_padding="12 8 12"
topbar_launcher_padding="10 4 10"
topbar_taskbar_padding="6 0 6"
dock_size="48% 58"
dock_margin="0 18"
dock_autohide="0"
dock_padding="14 9 14"
dock_launcher_padding="12 6 12"
rofi_main_spacing="12"
rofi_main_padding="14"
rofi_input_padding="12"
rofi_list_spacing="6"
rofi_element_padding="10"
dunst_width="320"
dunst_height="96"
dunst_offset="18x56"
dunst_padding="12"
dunst_horizontal_padding="12"
dunst_gap_size="8"
