ob_title_layout="NLC"
margin_top="48"
margin_bottom="64"
margin_left="8"
margin_right="8"
topbar_size="99% 40"
topbar_margin="8 8"
topbar_padding="10 6 10"
topbar_launcher_padding="8 3 8"
topbar_taskbar_padding="4 0 4"
dock_size="42% 52"
dock_margin="0 12"
dock_autohide="1"
dock_padding="10 7 10"
dock_launcher_padding="10 4 10"
rofi_main_spacing="10"
rofi_main_padding="12"
rofi_input_padding="10"
rofi_list_spacing="5"
rofi_element_padding="8"
dunst_width="280"
dunst_height="88"
dunst_offset="14x48"
dunst_padding="10"
dunst_horizontal_padding="10"
dunst_gap_size="6"
