ob_title_layout="NLIMC"
margin_top="64"
margin_bottom="90"
margin_left="20"
margin_right="20"
topbar_size="96% 48"
topbar_margin="14 12"
topbar_padding="16 10 16"
topbar_launcher_padding="12 5 12"
topbar_taskbar_padding="8 0 8"
dock_size="54% 64"
dock_margin="0 22"
dock_autohide="0"
dock_padding="18 12 18"
dock_launcher_padding="14 8 14"
rofi_main_spacing="14"
rofi_main_padding="18"
rofi_input_padding="14"
rofi_list_spacing="8"
rofi_element_padding="12"
dunst_width="360"
dunst_height="104"
dunst_offset="22x64"
dunst_padding="14"
dunst_horizontal_padding="14"
dunst_gap_size="10"
